### ISSUE TITLE
DomainException: Unrecognised or unsupported EC curve at apps/user_oidc/lib/Vendor/Firebase/JWT/JWK.php line 145

### ISSUE THREAD

**Issue by promasu** [nextcloud/user_oidc#823]
With certain configurations of Keycloak as OIDC the login fails and the above mentioned error is posted to the nextcloud log.
This regression was introduced by f7b68dd which bumped the version of firebase/php-jwt which contains the buggy code.

ref: https://github.com/firebase/php-jwt/issues/561

**Comment by DatNoHand** [comment]
Running into the same problem. What do we have to change on the Keycloak side in order to make login work again?

**Comment by zealousGnu** [comment]
We also have this issue and don't have the ability to remove this key on the keycloak side, so we can't use this app at all until this is fixed.

**Comment by bk1b** [comment]
I had the same problem, and my solution was to include these types of keys in Keycloak Keys.

At keycloak, go to “Realm settings” → “Keys” → “Providers” → “Add provider” → select `ecdsa-generated` and `ecdh-generated`

**Comment by strobelpierre** [comment]
Hi @promasu , @DatNoHand , @zealousGnu , @bk1b , i just pushed a PR on this issue tell me what do you think about my proposal , it's worked for me.

**Comment by zealousGnu** [comment]
I'm still having the same issue `"CustomMessage":"Unrecognised or unsupported EC curve"`

**Comment by bk1b** [comment]
@zealousGnu did you try to add `ecdsa-generated` and `ecdh-generated` keys at your Keycloak?

> go to “Realm settings” → “Keys” → “Providers” → “Add provider” → select `ecdsa-generated` and `ecdh-generated`

**Comment by zealousGnu** [comment]
<img width="2800" height="132" alt="Image" src="https://github.com/user-attachments/assets/626abb09-d7d6-47ae-9d68-597b2a49ec13" />

Yes.
